# Tema 6 Tecnologías del Habla


### Rebeca Goya Esteban y Óscar Barquero Pérez

update: 15 de noviembre de 2022

<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Licencia de Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />Este obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">licencia de Creative Commons Reconocimiento-NoComercial-CompartirIgual 4.0 Internacional</a>. 

## 6.2 Clasificadores Máquina

En este notebook vamos a aplicar tres técnicas de aprendizaje máquina para resolver un problema de clasificación.

**Descripción de los datos**: The iris data sets consists of 3 different types of irises’ (Setosa, Versicolour, and Virginica) petal and sepal length, stored in a 150x4 numpy.ndarray
The rows being the samples and the columns being: Sepal Length, Sepal Width, Petal Length and Petal Width.


En la siguiente celda se cargan los datos y se realiza una división de los mismos en un conjunto de entrenamiento y un conjunto de test. En *X_train* y *X_test* corresponden a carcterı́sticas de tres clases de flores, en total hay 150
ejemplos. En *y_train* y *y_test* se encuentra la información de a qué clase
pertenece cada una de las 150 flores (tres posibles clases).

**¿Cuántas características se están utilizando para representar/describir a cada una de las flores?**


In [1]:
%matplotlib inline
#imports
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np

#load datasets and split into test and train

iris = datasets.load_iris()
X = iris.data  
y = iris.target

#30% de test

#split train test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

## 6.2.1 Naive Bayes



Vamos a utilizar el Método de Clasificación de [Naïve Bayes GaussianNB](http://scikit-learn.org/stable/modules/naive_bayes.html#gaussian-naive-bayes), donde hay dos asunciones básicas:

* Asunción *naïve* de independencia condicional entre las características para una clase de la variable respuesta dada:

$$P(x_1,\ldots,x_d\mid y_i) = \prod_{k = 1}^{d}P(x_k\mid y_i)$$

* La verosimilitud de cada una de las características se asume Gaussiana:

$$P(x_i \mid y) = \frac{1}{\sqrt{2\pi\sigma^2_y}} \exp\left(-\frac{(x_i - \mu_y)^2}{2\sigma^2_y}\right)$$

## Entrenamiento

A continuación entrenamos el algoritmo, lo que implica calcular los parámetros $\mu_y$ y $\sigma_y$.

* Utilice los datos de entrenamiento (*X_Train* y *y_Train*) y la función *GaussianNB.fit()* para estimar los parámetros de la pdf gaussiana de cada una de las 3 clases de flores.

In [4]:
from sklearn.naive_bayes import GaussianNB

# Creamos el modelo de NB

model_NB = GaussianNB()

#entrenamos

model_NB.fit(X_train, y_train)

print(X_train)


[[5.3 3.7 1.5 0.2]
 [5.6 2.9 3.6 1.3]
 [6.5 3.  5.2 2. ]
 [7.2 3.  5.8 1.6]
 [6.6 2.9 4.6 1.3]
 [6.1 2.8 4.  1.3]
 [5.8 2.7 5.1 1.9]
 [7.  3.2 4.7 1.4]
 [6.1 3.  4.9 1.8]
 [5.7 2.8 4.1 1.3]
 [4.8 3.4 1.9 0.2]
 [6.3 2.3 4.4 1.3]
 [6.5 3.  5.8 2.2]
 [4.9 3.1 1.5 0.1]
 [7.7 2.8 6.7 2. ]
 [4.8 3.  1.4 0.1]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [4.4 3.  1.3 0.2]
 [5.2 2.7 3.9 1.4]
 [5.1 3.7 1.5 0.4]
 [6.9 3.1 4.9 1.5]
 [7.9 3.8 6.4 2. ]
 [6.8 3.2 5.9 2.3]
 [5.4 3.  4.5 1.5]
 [6.4 2.8 5.6 2.1]
 [5.  3.4 1.6 0.4]
 [4.6 3.2 1.4 0.2]
 [6.2 3.4 5.4 2.3]
 [5.6 2.8 4.9 2. ]
 [6.2 2.9 4.3 1.3]
 [4.3 3.  1.1 0.1]
 [4.6 3.4 1.4 0.3]
 [6.7 3.1 4.4 1.4]
 [6.3 3.3 4.7 1.6]
 [6.5 3.2 5.1 2. ]
 [6.3 2.7 4.9 1.8]
 [5.9 3.  5.1 1.8]
 [7.3 2.9 6.3 1.8]
 [6.  2.2 5.  1.5]
 [5.1 3.8 1.9 0.4]
 [5.5 3.5 1.3 0.2]
 [7.1 3.  5.9 2.1]
 [6.4 2.8 5.6 2.2]
 [5.7 3.  4.2 1.2]
 [5.1 3.3 1.7 0.5]
 [5.  3.6 1.4 0.2]
 [6.9 3.2 5.7 2.3]
 [5.7 4.4 1.5 0.4]
 [6.7 3.1 5.6 2.4]
 [5.4 3.4 1.5 0.4]
 [6.3 2.9 5.6 1.8]
 [6.7 3.3 5.

In [5]:
# Media y desviación estándar para las características de cada clase:

print("Media de la gaussiana para cada clase:\n Columnas = Características \n Filas = Clases\n")
print(model_NB.theta_)

Media de la gaussiana para cada clase:
 Columnas = Características 
 Filas = Clases

[[5.03225806 3.40967742 1.47096774 0.26129032]
 [5.92222222 2.76944444 4.24166667 1.32777778]
 [6.58684211 2.99473684 5.56842105 2.04210526]]


In [6]:
print("Desviación estándar de la gaussiana para cada clase:\n Columnas = Características \n Filas = Clases\n")
print(model_NB.sigma_)

Desviación estándar de la gaussiana para cada clase:
 Columnas = Características 
 Filas = Clases

[[0.12734652 0.10861603 0.02915713 0.01334027]
 [0.30228395 0.11934414 0.22909723 0.03811729]
 [0.39377424 0.10891967 0.29952909 0.06296399]]


## Test
* Clasifique cada ejemplo (flor) de los datos de test (x test iris y y test iris) de acuerdo al esquema de clasificación Naive Bayes. Para ello, utilice *model_NB.predict(X_test)*
* Calcule el error de clasificación.

In [7]:
# Predecimos las muestras de test, utilizando los valores de la función estimados anteriorment en train

y_hat_NB = model_NB.predict(X_test)

#Calculamos el accuracy (exactitud = mº de actiertos/nº de casos totales)

acc_NB = np.mean(y_test == y_hat_NB)
print(acc_NB)
print(y_hat_NB)
print(y_test)
print(X_test)


0.9555555555555556
[2 2 0 1 2 0 1 0 2 1 1 1 1 0 1 0 1 1 1 0 0 1 0 0 2 0 0 2 0 2 2 1 2 1 0 1 0
 1 1 0 0 0 2 0 0]
[2 2 0 2 2 0 1 0 2 1 1 1 1 0 1 0 1 1 1 0 0 1 0 0 2 0 0 2 0 2 2 1 2 1 0 1 0
 1 2 0 0 0 2 0 0]
[[6.9 3.1 5.4 2.1]
 [6.  3.  4.8 1.8]
 [4.4 3.2 1.3 0.2]
 [6.3 2.8 5.1 1.5]
 [5.8 2.8 5.1 2.4]
 [4.6 3.6 1.  0.2]
 [5.6 3.  4.1 1.3]
 [4.8 3.4 1.6 0.2]
 [6.2 2.8 4.8 1.8]
 [6.  2.9 4.5 1.5]
 [6.8 2.8 4.8 1.4]
 [5.8 2.6 4.  1.2]
 [6.  2.7 5.1 1.6]
 [5.1 3.4 1.5 0.2]
 [5.8 2.7 4.1 1. ]
 [4.8 3.1 1.6 0.2]
 [6.6 3.  4.4 1.4]
 [5.9 3.  4.2 1.5]
 [5.6 3.  4.5 1.5]
 [4.7 3.2 1.6 0.2]
 [5.  3.3 1.4 0.2]
 [6.3 2.5 4.9 1.5]
 [5.  3.4 1.5 0.2]
 [4.5 2.3 1.3 0.3]
 [7.2 3.6 6.1 2.5]
 [5.  3.2 1.2 0.2]
 [5.4 3.4 1.7 0.2]
 [6.7 2.5 5.8 1.8]
 [5.1 3.8 1.6 0.2]
 [7.7 3.  6.1 2.3]
 [7.6 3.  6.6 2.1]
 [5.5 2.4 3.7 1. ]
 [6.8 3.  5.5 2.1]
 [5.6 2.7 4.2 1.3]
 [5.1 3.8 1.5 0.3]
 [5.7 2.6 3.5 1. ]
 [5.5 4.2 1.4 0.2]
 [6.4 2.9 4.3 1.3]
 [6.1 2.6 5.6 1.4]
 [5.2 4.1 1.5 0.1]
 [4.4 2.9 1.4 0.2]
 [5.4 3.9 1.3 0.

## 6.2.2 Ejemplo KNN con sklearn

Vamos a utilizar el método de clasificación KNN https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

**Pruebe diferentes valores para el parámetro K**

In [8]:
from sklearn.neighbors import KNeighborsClassifier 

model_KNN = KNeighborsClassifier(n_neighbors=3)

#train the model 

model_KNN.fit(X_train, y_train)

#predict outputs

y_hat_KNN = model_KNN.predict(X_test)

#accuracy

acc = np.mean(y_test == y_hat_KNN)

print(acc)
print(X_train)

0.9555555555555556
[[5.3 3.7 1.5 0.2]
 [5.6 2.9 3.6 1.3]
 [6.5 3.  5.2 2. ]
 [7.2 3.  5.8 1.6]
 [6.6 2.9 4.6 1.3]
 [6.1 2.8 4.  1.3]
 [5.8 2.7 5.1 1.9]
 [7.  3.2 4.7 1.4]
 [6.1 3.  4.9 1.8]
 [5.7 2.8 4.1 1.3]
 [4.8 3.4 1.9 0.2]
 [6.3 2.3 4.4 1.3]
 [6.5 3.  5.8 2.2]
 [4.9 3.1 1.5 0.1]
 [7.7 2.8 6.7 2. ]
 [4.8 3.  1.4 0.1]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [4.4 3.  1.3 0.2]
 [5.2 2.7 3.9 1.4]
 [5.1 3.7 1.5 0.4]
 [6.9 3.1 4.9 1.5]
 [7.9 3.8 6.4 2. ]
 [6.8 3.2 5.9 2.3]
 [5.4 3.  4.5 1.5]
 [6.4 2.8 5.6 2.1]
 [5.  3.4 1.6 0.4]
 [4.6 3.2 1.4 0.2]
 [6.2 3.4 5.4 2.3]
 [5.6 2.8 4.9 2. ]
 [6.2 2.9 4.3 1.3]
 [4.3 3.  1.1 0.1]
 [4.6 3.4 1.4 0.3]
 [6.7 3.1 4.4 1.4]
 [6.3 3.3 4.7 1.6]
 [6.5 3.2 5.1 2. ]
 [6.3 2.7 4.9 1.8]
 [5.9 3.  5.1 1.8]
 [7.3 2.9 6.3 1.8]
 [6.  2.2 5.  1.5]
 [5.1 3.8 1.9 0.4]
 [5.5 3.5 1.3 0.2]
 [7.1 3.  5.9 2.1]
 [6.4 2.8 5.6 2.2]
 [5.7 3.  4.2 1.2]
 [5.1 3.3 1.7 0.5]
 [5.  3.6 1.4 0.2]
 [6.9 3.2 5.7 2.3]
 [5.7 4.4 1.5 0.4]
 [6.7 3.1 5.6 2.4]
 [5.4 3.4 1.5 0.4]
 [6.3 2.9 5.

## 6.2.3 redes neuronales

Vamos a utilizar el método de clasificación redes neuronales https://scikit-learn.org/stable/modules/neural_networks_supervised.html

https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html#sklearn.neural_network.MLPClassifier

**Pruebe diferentes configuraciones de capas y neuronas ocultas**

**Pruebe o modificar otros parámetros de la red neuronal**


In [21]:
from sklearn.neural_network import MLPClassifier

model_RN = MLPClassifier(hidden_layer_sizes=(1,10)) #nº capas, nº neuronas

#train the model 

model_RN.fit(X_train, y_train)

#predict outputs
y_hat_RN = model_RN.predict(X_test)

#accuracy

acc = np.mean(y_test == y_hat_RN)

print(acc)

0.8888888888888888


/usr/lib/python3/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
